ca/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
@date: 2018-06-02
@author: Shell.Xu
@copyright: 2018, Shell.Xu <shell909090@gmail.com>
@license: BSD-3-clause
'''
from django.conf.urls import url

from . import views


app_name = 'ca'
urlpatterns = [
    url(r'^k/',
        views.list_key, name='list_key'),
    url(r'^dk/(?P<dgst>[0-9A-F]{16})',
        views.detail_key, name='detail_key'),
    url(r'^rk/(?P<dgst>[0-9A-F]{16})',
        views.remove_key, name='remove_key'),
    url(r'^brsa',
        views.build_rsa, name='build_rsa'),
    url(r'^bec',
        views.build_ec, name='build_ec'),
    url(r'^enc/(?P<dgst>[0-9A-F]{16})',
        views.encrypt, name='encrypt'),
    url(r'^dec/(?P<dgst>[0-9A-F]{16})',
        views.decrypt, name='decrypt'),
    url(r'^sig/(?P<dgst>[0-9A-F]{16})',
        views.sign, name='sign'),
    url(r'^vrf/(?P<dgst>[0-9A-F]{16})',
        views.verify, name='verify'),
    url(r'^ik',
        views.import_key, name='import_key'),
    url(r'^ek/(?P<dgst>[0-9A-F]{16})',
        views.export_key, name='export_key'),
    url(r'^epk/(?P<dgst>[0-9A-F]{16})',
        views.export_pubkey, name='export_pubkey'),
    url(r'^es/(?P<dgst>[0-9A-F]{16})',
        views.export_sshpub, name='export_sshpub'),
    url(r'^br/(?P<dgst>[0-9A-F]{16})',
        views.build_req, name='build_req'),

    url(r'^c/(?P<dgst>[0-9A-F]{0,16})',
        views.list_cert, name='list_cert'),
    url(r'^dc/(?P<dgst>[0-9A-F]{16})',
        views.detail_cert, name='detail_cert'),
    url(r'^ip',
        views.import_pem, name='import_pem'),
    url(r'^rc/(?P<dgst>[0-9A-F]{16})',
        views.remove_cert, name='remove_cert'),
    url(r'^bc/(?P<dgst>[0-9A-F]{16})',
        views.build_cert, name='build_cert'),
    url(r'^sr/(?P<dgst>[0-9A-F]{16})',
        views.sign_req, name='sign_req'),
    url(r'^ep/(?P<dgst>[0-9A-F]{16})',
        views.export_pem, name='export_pem'),
    url(r'^ed/(?P<dgst>[0-9A-F]{16})',
        views.export_der, name='export_der'),
    url(r'^ec/(?P<dgst>[0-9A-F]{16})',
        views.export_chain, name='export_chain'),
    url(r'^ep12/(?P<dgst>[0-9A-F]{16})',
        views.export_pkcs12, name='export_pkcs12'),
    url(r'^rvk/(?P<dgst>[0-9A-F]{16})',
        views.revoke_cert, name='revoke_cert'),
    url(r'^urvk/(?P<dgst>[0-9A-F]{16})',
        views.unrevoke_cert, name='unrevoke_cert'),
    url(r'^(?P<dgst>[0-9A-F]{16}).crl',
        views.show_crl, name='show_crl'),
]

clayton/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ca.urls')),
]

ca/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class PubKey(models.Model):

    KEY_CHOICES = (
        (1, 'RSAPrivateKey'),
        (2, 'RSAPublicKey'),
        (3, 'ECCPrivateKey'),
        (4, 'ECCPublicKey'),
    )

    dgst = models.CharField(max_length=33, primary_key=True)
    keytype = models.IntegerField(choices=KEY_CHOICES)
    size = models.IntegerField()
    dat = models.BinaryField()

    def cert_count(self):
        return Cert.objects.filter(key=self).count()

    def __str__(self):
        return self.dgst


class Cert(models.Model):
    dgst = models.CharField(max_length=33, primary_key=True)
    status = models.IntegerField()
    sn = models.CharField(max_length=30)
    sub = models.CharField(max_length=200)
    cn = models.CharField(max_length=100)
    notbefore = models.DateTimeField()
    notafter = models.DateTimeField()
    issuer = models.ForeignKey(
        'self', null=True,
        on_delete=models.DO_NOTHING, db_constraint=False)
    ca = models.BooleanField()
    authkeyid = models.CharField(max_length=65)
    keyid = models.CharField(max_length=65)
    alternative = models.TextField(null=True)
    dat = models.BinaryField()
    key = models.ForeignKey(
        'PubKey', null=True, related_name='certs',
        on_delete=models.DO_NOTHING, db_constraint=False)

    class Meta:
        unique_together = (
            ("issuer", "sn"),
        )

    def __str__(self):
        return self.dgst

    def signed_count(self):
        return Cert.objects.filter(issuer=self).count()

ca/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
@date: 2018-06-04
@author: Shell.Xu
@copyright: 2018, Shell.Xu <shell909090@gmail.com>
@license: BSD-3-clause
'''
from __future__ import absolute_import, division,\
    print_function, unicode_literals
from django import forms

from cryptography.x509.oid import ExtendedKeyUsageOID

from . import crypt


class BuildRSAForm(forms.Form):
    size = forms.IntegerField(initial=2048)


class BuildECForm(forms.Form):
    curve_names = sorted(crypt.CURVE_MAPPING.keys())
    CURVE_CHOICES = zip(curve_names, curve_names)
    curve = forms.ChoiceField(choices=CURVE_CHOICES, initial='secp256r1')


class TextForm(forms.Form):
    txt = forms.CharField(widget=forms.Textarea)


class DoubleTextForm(forms.Form):
    txt1 = forms.CharField(widget=forms.Textarea)
    txt2 = forms.CharField(widget=forms.Textarea)


class UploadForm(forms.Form):
    upload = forms.FileField()


EXT_USAGE_CHOICES = (
    ('', '--'),
    (ExtendedKeyUsageOID.SERVER_AUTH._name,
     'SSL/TLS Web Server Authentication'),
    (ExtendedKeyUsageOID.CLIENT_AUTH._name,
     'SSL/TLS Web Client Authentication'),
    (ExtendedKeyUsageOID.CODE_SIGNING._name,
     'Code signing'),
    (ExtendedKeyUsageOID.EMAIL_PROTECTION._name,
     'E-mail Protection (S/MIME)'),
    (ExtendedKeyUsageOID.TIME_STAMPING._name,
     'Trusted Timestampin'),
    (ExtendedKeyUsageOID.OCSP_SIGNING._name,
     'OCSP Signin'),
)


class ReqForm(forms.Form):
    cn = forms.CharField(max_length=50)
    country = forms.CharField(max_length=3, required=False)
    province = forms.CharField(max_length=10, required=False)
    city = forms.CharField(max_length=30, required=False)
    org = forms.CharField(max_length=30, required=False)
    email = forms.CharField(max_length=50, required=False)
    ou = forms.CharField(max_length=30, required=False)
    alternative = forms.CharField(max_length=200, required=False,
                                  widget=forms.Textarea)
    usage = forms.ChoiceField(choices=EXT_USAGE_CHOICES, required=False)
    ca = forms.BooleanField(required=False)
    selfsign = forms.BooleanField(required=False)


class SignConfirmForm(forms.Form):
    csr = forms.CharField(max_length=100000,
                          widget=forms.HiddenInput())
    days = forms.CharField(max_length=5, required=False)

ca/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import binascii

from django import forms
from django.core import exceptions as djerr
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

from cryptography import exceptions
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

from . import crypt
from .models import PubKey, Cert
from . import forms as caforms
from . import tables, filters

# FIXME: is it possible that csr caused XSS?

# key


def list_key(request):
    okeys = PubKey.objects.all()
    f = filters.PubKeyFilter(request.GET, queryset=okeys)
    table = tables.PubKeyTable(f.qs, request=request)
    formrsa = caforms.BuildRSAForm()
    formec = caforms.BuildECForm()
    formup = caforms.UploadForm()
    p = {
        'table': table,
        'filter': f,
        'formrsa': formrsa,
        'formec': formec,
        'formup': formup,
    }
    return render(request, 'ca/list_key.html', p)


def detail_key(request, dgst):
    obj = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(obj.dat)
    p = crypt.parse_privatekey(pkey)
    certs = Cert.objects.filter(key_id=dgst).all()
    tab = tables.CertTable(certs, request=request)
    pm = {
        'obj': obj,
        'p': p,
        'rsa': p['type'].startswith('RSA'),
        'tab': tab,
    }
    return render(request, 'ca/detail_key.html', pm)


def remove_key(request, dgst):
    okey = PubKey.objects.get(dgst=dgst)
    okey.delete()
    return HttpResponseRedirect(reverse('ca:list_key'))


def build_rsa(request):
    if request.method != 'POST':
        # form = caforms.BuildRSAForm()
        # p = {'title': 'build rsa', 'form': form}
        # return render(request, 'ca/post.html', p)
        return HttpResponseRedirect(reverse('ca:list_key'))
    form = caforms.BuildRSAForm(request.POST)
    if not form.is_valid():
        # p = {'title': 'build rsa', 'form': form}
        # return render(request, 'ca/post.html', p)
        # FIXME: msg
        return HttpResponseRedirect(reverse('ca:list_key'))
    size = form.cleaned_data['size']
    pkey = crypt.generate_rsa(size)
    bkey = crypt.dump_privatekey(pkey)
    dgst = crypt.get_keyid(pkey)
    okey = PubKey(dgst=dgst, keytype=1, size=size, dat=bkey)
    okey.save()
    return HttpResponseRedirect(reverse('ca:list_key'))


def build_ec(request):
    if request.method != 'POST':
        # form = caforms.BuildECForm()
        # p = {'title': 'build ec', 'form': form}
        # return render(request, 'ca/post.html', p)
        return HttpResponseRedirect(reverse('ca:list_key'))
    form = caforms.BuildECForm(request.POST)
    if not form.is_valid():
        # p = {'title': 'build ec', 'form': form}
        # return render(request, 'ca/post.html', p)
        return HttpResponseRedirect(reverse('ca:list_key'))
    curve = form.cleaned_data['curve']
    pkey = crypt.generate_ec(curve)
    size = pkey.public_key().public_numbers().curve.key_size
    bkey = crypt.dump_privatekey(pkey)
    dgst = crypt.get_keyid(pkey)
    okey = PubKey(dgst=dgst, keytype=3, size=size, dat=bkey)
    okey.save()
    return HttpResponseRedirect(reverse('ca:list_key'))


def encrypt(request, dgst):
    if request.method != 'POST':
        form = caforms.TextForm()
        p = {'title': 'encrypt message', 'form': form}
        return render(request, 'ca/post.html', p)
    form = caforms.TextForm(request.POST)
    if not form.is_valid():
        p = {'title': 'encrypt message', 'form': form}
        return render(request, 'ca/post.html', p)
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    msg = form.cleaned_data['txt'].encode('utf-8')
    enc = pkey.public_key().encrypt(msg, crypt.OAEP)
    p = {
        'title': 'encrypt message',
        'msg': binascii.b2a_base64(enc).decode('utf-8')
    }
    return render(request, 'ca/show_msg.html', p)


def decrypt(request, dgst):
    if request.method != 'POST':
        form = caforms.TextForm()
        p = {'title': 'decrypt message', 'form': form}
        return render(request, 'ca/post.html', p)
    form = caforms.TextForm(request.POST)
    if not form.is_valid():
        p = {'title': 'decrypt message', 'form': form}
        return render(request, 'ca/post.html', p)
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    enc = binascii.a2b_base64(form.cleaned_data['txt'])
    msg = pkey.decrypt(enc, crypt.OAEP)
    p = {
        'title': 'decrypt message',
        'msg': msg.decode('utf-8'),
    }
    return render(request, 'ca/show_msg.html', p)


def sign(request, dgst):
    if request.method != 'POST':
        form = caforms.TextForm()
        p = {'title': 'sign message', 'form': form}
        return render(request, 'ca/post.html', p)
    form = caforms.TextForm(request.POST)
    if not form.is_valid():
        p = {'title': 'sign message', 'form': form}
        return render(request, 'ca/post.html', p)
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    msg = form.cleaned_data['txt'].encode('utf-8')
    sig = crypt.pubkey_sign(pkey, msg)
    p = {
        'title': 'sign message',
        'msg': binascii.b2a_base64(sig).decode('utf-8'),
    }
    return render(request, 'ca/show_msg.html', p)


def verify(request, dgst):
    if request.method != 'POST':
        form = caforms.DoubleTextForm()
        p = {'title': 'verify sign', 'form': form}
        return render(request, 'ca/post.html', p)
    form = caforms.DoubleTextForm(request.POST)
    if not form.is_valid():
        p = {'title': 'verify sign', 'form': form}
        return render(request, 'ca/post.html', p)
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    msg = form.cleaned_data['txt1'].encode('utf-8')
    sig = binascii.a2b_base64(form.cleaned_data['txt2'])
    try:
        crypt.pubkey_verify(pkey.public_key(), msg, sig)
        msg = 'OK'
    except exceptions.InvalidSignature:
        msg = 'failed'
    p = {
        'title': 'verify sign',
        'msg': msg,
    }
    return render(request, 'ca/show_msg.html', p)


def imp_key(bkey):
    pkey = crypt.load_privatekey(bkey)
    dgst = crypt.get_keyid(pkey)
    p = crypt.parse_privatekey(pkey)
    typeid = {v: k for k, v in PubKey.KEY_CHOICES}[p['type']]
    q = PubKey.objects.filter(dgst=dgst)
    if q.count() == 0:
        okey = PubKey(dgst, keytype=typeid, size=p['size'], dat=bkey)
        okey.save()
    else:
        okey = q.get()
    return okey


def import_key(request):
    if request.method != 'POST':
        # form = caforms.UploadForm()
        # p = {'title': 'import key', 'form': form}
        # return render(request, 'ca/post_file.html', p)
        return HttpResponseRedirect(reverse('ca:list_key'))
    form = caforms.UploadForm(request.POST, request.FILES)
    if not form.is_valid():
        # p = {'title': 'import key', 'form': form}
        # return render(request, 'ca/post_file.html', p)
        return HttpResponseRedirect(reverse('ca:list_key'))
    imp_key(form.cleaned_data['upload'].read())
    return HttpResponseRedirect(reverse('ca:list_key'))


def export_key(request, dgst):
    okey = PubKey.objects.get(dgst=dgst)
    resp = HttpResponse(okey.dat, content_type="application/x-pem-file")
    resp['Content-Disposition'] = 'inline; filename=%s.pem' % okey.dgst
    return resp


def export_pubkey(request, dgst):
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    bpub = crypt.dump_publickey(pkey.public_key())
    resp = HttpResponse(bpub, content_type="application/x-pem-file")
    resp['Content-Disposition'] = 'inline; filename=%s.pem' % okey.dgst
    return resp


def export_sshpub(request, dgst):
    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    bpub = crypt.dump_publickey(
        pkey.public_key(),
        encoding=Encoding.OpenSSH,
        format=PublicFormat.OpenSSH)
    p = {'title': 'ssh public key', 'msg': bpub.decode('utf-8')}
    return render(request, 'ca/show_msg.html', p)


def build_req(request, dgst):
    if request.method != 'POST':
        form = caforms.ReqForm()
        p = {'title': 'build cert request', 'form': form}
        return render(request, 'ca/post.html', p)
    form = caforms.ReqForm(request.POST)
    if not form.is_valid():
        p = {'title': 'build cert request', 'form': form}
        return render(request, 'ca/post.html', p)

    okey = PubKey.objects.get(dgst=dgst)
    pkey = crypt.load_privatekey(okey.dat)
    csr = crypt.generate_req(pkey, form.cleaned_data)

    if form.cleaned_data['selfsign']:
        cert = crypt.selfsign_req(csr, pkey)
        bcert = crypt.dump_certificate(cert)
        ocert = imp_cert(bcert)
        return HttpResponseRedirect(
            reverse('ca:detail_cert', kwargs={'dgst': ocert.dgst}))

    bcsr = crypt.dump_certificate_request(csr)
    resp = HttpResponse(bcsr, content_type="application/x-pem-file")
    resp['Content-Disposition'] = 'inline; filename=%s.csr' % okey.dgst
    return resp


# cert


def list_cert(request, dgst):
    q = Cert.objects
    if dgst:
        q = q.filter(dgst=dgst)
    f = filters.CertFilter(request.GET, queryset=q.all())
    table = tables.CertTable(f.qs, request=request)
    formup = caforms.UploadForm()
    p = {
        'table': table,
        'filter': f,
        'formup': formup,
    }
    return render(request, 'ca/list_cert.html', p)


def detail_cert(request, dgst):
    obj = Cert.objects.get(dgst=dgst)
    cert = crypt.load_certificate(obj.dat)
    reader = crypt.CertReader(cert)
    certs = Cert.objects.filter(issuer=obj).all()
    table = tables.CertTable(certs, request=request)
    formup = caforms.UploadForm()

    def getchain():
        c = obj
        while c:
            yield c
            c = c.issuer
    chain = list(reversed(list(getchain())))

    p = {
        'obj': obj,
        'reader': reader,

ca/templates/ca/base.html
{% load bootstrap3 %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title>{%block title%}{%endblock%}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="author" content="shell">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
      body {
        font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;
      }
    </style>
    {% block header %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
	<div class="navbar-header">
	  <a class="navbar-brand" href="#">CA manager</a>
	</div>
	<ul class="nav navbar-nav">
	  <li><a href="{% url 'ca:list_key' %}">Keys</a></li>
	  <li><a href="{% url 'ca:list_cert' '' %}">Certs</a></li>
	</ul>
	{% block nav_left %}
	{% endblock %}
	<ul class="nav navbar-nav navbar-right">
	  {% block nav_right %}
	  {% endblock %}
	</ul>
      </div>
    </nav>

    {% bootstrap_messages %}

    <div class="container">
      {%block body%}
      {%endblock%}
    </div>
    
    {% block script %}
    {% endblock %}
  </body>
</html>

ca/templates/ca/detail_cert.html
{% extends 'ca/base.html' %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block title %}detail cert{% endblock %}

{% block body %}

<table class="table-striped table-condensed table-responsive">
  <tbody>
    <tr>
      <td>dgst</td>
      <td>{{obj.dgst}}</td>
    </tr>
    <tr>
      <td>sn</td>
      <td>{{obj.sn}}</td>
    </tr>
    <tr>
      <td>notbefore</td>
      <td>{{obj.notbefore}}</td>
    </tr>
    <tr>
      <td>notafter</td>
      <td>{{obj.notafter}}</td>
    </tr>
    <tr>
      <td>subject</td>
      <td>{{obj.sub}}</td>
    </tr>
    <tr>
      <td>common name</td>
      <td>{{obj.cn}}</td>
    </tr>
    <tr>
      <td>CA</td>
      <td>{{reader.ca}}</td>
    </tr>
    <tr>
      <td>subject keyid</td>
      <td>{{obj.keyid}}</td>
    </tr>
    <tr>
      <td>auth keyid</td>
      <td>{{reader.authkeyid}}</td>
    </tr>
    <tr>
      <td>extended key usage</td>
      <td>{{reader.extusage}}</td>
    </tr>
    <tr>
      <td>key usage</td>
      <td>{{reader.usage}}</td>
    </tr>
    <tr>
      <td>alternative</td>
      <td>{{obj.alternative}}</td>
    </tr>
    <tr>
      <td>key</td>
      <td>
	{% if obj.key %}
	<a href="{% url 'ca:detail_key' obj.key_id %}">
	  {{obj.key.dgst}}
	</a>
	{% endif %}
      </td>
    </tr>
    <tr>
      <td>chain</td>
      <td>
	{% for c in chain %}
	<div class="row">
	<a href="{% url 'ca:detail_cert' c.dgst %}" title="{{c.sub}}">
	  {{c.dgst}} {{c.cn}}
	</a>
	</div>
	{% endfor %}
      </td>
  </tbody>
</table>

{% render_table table %}

<div id="sign_req" class="modal fade" role="dialog">
  <form class="form-horizontal" action="{% url 'ca:sign_req' obj.dgst %}" method="POST" enctype="multipart/form-data">
    <div class="modal-dialog">
      <div class="modal-content">
	<div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">sign req</h4>
	</div>
	<div class="modal-body">
	  {% csrf_token %}
	  {% bootstrap_form formup layout="horizontal" %}
	</div>
	<div class="modal-footer">
	  <button type="submit" class="btn btn-primary">Submit</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	</div>
      </div>
    </div>
  </form>
</div>

{% endblock %}

{% block nav_right %}
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Ops
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'ca:export_pem' obj.dgst %}">export pem</a></li>
    <li><a href="{% url 'ca:export_der' obj.dgst %}">export der</a></li>
    <li><a href="{% url 'ca:export_chain' obj.dgst %}">export chain</a></li>
    <li><a href="{% url 'ca:export_pkcs12' obj.dgst %}">export pkcs12</a></li>
    {% if obj.ca and obj.key %}
    <li><a data-toggle="modal" data-target="#sign_req">sign req</a></li>
    <li><a href="{% url 'ca:build_cert' obj.dgst %}">build cert</a></li>
    {% endif %}
    {% if obj.status == 0 %}
    <li><a href="{% url 'ca:revoke_cert' obj.dgst %}">revoke</a></li>
    {% endif %}
    {% if obj.status == 42 %}
    <li><a href="{% url 'ca:revoke_cert' obj.dgst %}">unrevoke</a></li>
    {% endif %}
  </ul>
</li>
{% endblock %}

ca/templates/ca/detail_key.html
{% extends 'ca/base.html' %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block title %}key detail{% endblock %}

{% block body %}
<table class="table-striped table-condensed table-responsive" width="100%" style="table-layout: fixed;">
  <tbody>
    <tr>
      <td width="10%">dgst</td>
      <td>{{obj.dgst}}</td>
    </tr>
    <tr>
      <td>type</td>
      <td>{{p.type}}</td>
    </tr>
    <tr>
      <td>size</td>
      <td>{{p.size}}</td>
    </tr>
    {% if p.n %}
    <tr>
      <td>n</td>
      <td style="word-wrap: break-word;">{{p.n}}</td>
    </tr>
    {% endif %}
    {% if p.e %}
    <tr>
      <td>e</td>
      <td style="word-wrap: break-word;">{{p.e}}</td>
    </tr>
    {% endif %}
    {% if p.d %}
    <tr>
      <td>d</td>
      <td style="word-wrap: break-word;">{{p.d}}</td>
    </tr>
    {% endif %}
    {% if p.p %}
    <tr>
      <td>p</td>
      <td style="word-wrap: break-word;">{{p.p}}</td>
    </tr>
    {% endif %}
    {% if p.q %}
    <tr>
      <td>q</td>
      <td style="word-wrap: break-word;">{{p.q}}</td>
    </tr>
    {% endif %}
    {% if p.curve %}
    <tr>
      <td>curve</td>
      <td>{{p.curve}}</td>
    </tr>
    {% endif %}
    {% if p.x %}
    <tr>
      <td>x</td>
      <td style="word-wrap: break-word;">{{p.x}}</td>
    </tr>
    {% endif %}
    {% if p.y %}
    <tr>
      <td>y</td>
      <td style="word-wrap: break-word;">{{p.y}}</td>
    </tr>
    {% endif %}
    {% if p.private %}
    <tr>
      <td>private</td>
      <td style="word-wrap: break-word;">{{p.private}}</td>
    </tr>
    {% endif %}
  </tbody>
</table>

{% render_table tab %}
{% endblock %}

{% block nav_right %}
<li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    Ops
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="{% url 'ca:export_key' obj.dgst %}">export key</a></li>
    <li><a href="{% url 'ca:export_pubkey' obj.dgst %}">export pubkey</a></li>
    <li><a href="{% url 'ca:export_sshpub' obj.dgst %}">export sshpub</a></li>
    <li><a href="{% url 'ca:build_req' obj.dgst %}">build req</a></li>
    {% if rsa %}
    <li><a href="{% url 'ca:encrypt' obj.dgst %}">encrypt</a></li>
    <li><a href="{% url 'ca:decrypt' obj.dgst %}">decrypt</a></li>
    {% endif %}
    <li><a href="{% url 'ca:sign' obj.dgst %}">sign</a></li>
    <li><a href="{% url 'ca:verify' obj.dgst %}">verify</a></li>
  </ul>
</li>
{% endblock %}

ca/templates/ca/show_msg.html
{% extends 'ca/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block body %}
<div style="word-wrap: break-word;" width="100%">
  {{msg}}
</div>
{% endblock %}

ca/templates/ca/sign_confirm.html
{% extends 'ca/base.html' %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block title %}sign confirm{% endblock %}

{% block body %}
<table class="table-striped table-condensed table-responsive">
  <tbody>
    <tr>
      <td>subject</td>
      <td>{{obj.subject}}</td>
    </tr>
    <tr>
      <td>common name</td>
      <td>{{obj.cn}}</td>
    </tr>
    {% for k, v in obj.extensions %}
    <tr>
      <td>{{k}}</td>
      <td>{{v}}</td>
    </tr>
    {% endfor %}
    <tr>
      <td>key</td>
      <td>
	<a href="{% url 'ca:detail_key' obj.keyid %}">
	  {{obj.keyid}}
	</a>
      </td>
    </tr>
  </tbody>
</table>

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>
{% endblock %}